xyz.jpenilla.run-paper.updateCheckFrequency=12h
version=VersionPlaceholder
org.jetbrains.dokka.experimental.gradle.pluginMode=V2Enabled
org.jetbrains.dokka.experimental.gradle.pluginMode.noWarn=true
# Gradle Properties
org.gradle.caching=true
org.gradle.daemon=true
org.gradle.parallel=true
# 設定フェーズの結果を再利用し、2 回目以降のビルドでビルドスクリプトの評価を省く
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx2G
